l=['a','b','c','d','d','e','f']
print(len(l))
l.append('h')
print(l)
l2=['k','l','m','n','o']
l.extend(l2)
print(l)
l.insert(2,'z')
print(l)
print('deleting',l.pop(2))
print('deleting',l.pop())
l.remove('a')
print(l)
l.reverse()
print(l)
l.sort
print(l)
print(l.count('a'))