str="hello world"
print(len(str))
print(str.index("o"))
print(str.index('o',5))
print(str.index('o',5,7))
print(str.count("l"))
print(str.upper())
print(str.lower())
print(str.startswith("hello"))
print(str.endswith("d!"))
words=str.split(" ")
print(words)
print(str.find('o'))
print(str.find('o',4))
print(str.find('o',5,7))
print(str.replace("world","python"))
